<?php
/**
 * Company Custom Fields.
 * @category: Magento
 * @package: Perficient/Company
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Sachin Badase <Sachin.Badase@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_Company
 */
use Magento\Company\Block\Company\Account\Create;
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Directory\Helper\Data as DirectoryHelper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * Create account form template
 *
 * @var Create $block
 * @var SecureHtmlRenderer $secureRenderer
 */
$viewModel = $block->getData('company_view_model');

?>
<form class="form create account form-create-account"
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Company Information')) ?></span></legend>
        <div class="field company-name required">
            <label class="label" for="company_name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[company_name]" id="company_name"
                       autocomplete="organization"
                       value=""
                       data-validate="{required:true, maxlength:50}"
                       class="input-text">
            </div>
        </div>
        <div class="field company-email required">
            <label class="label" for="company_email">
                <span><?= $block->escapeHtml(__('Company Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="company[company_email]" id="company_email"
                       value=""
                       autocomplete="email"
                       class="input-text"
                       data-role="email"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
"name": "company_email",
"validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
}}'
                       data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
            </div>
        </div>
        <div class="field newsletter">
                <span class="label">
                    <?= $block->escapeHtml(__('Sign Up for Newsletter')) ?>
                </span><br role="presentation" /><br role="presentation" />
            <div class="field control radiobtn-inline">
                <input type="radio"
                       name="company[newsletter]"
                       value="yes"
                       id="newsletter1"
                       class="checkbox"/>
                <label for="newsletter1">
                    <?= $block->escapeHtml(__('Yes')) ?>&nbsp;&nbsp;
                </label>
            </div>
            <div class="field control radiobtn-inline">
                <input type="radio"
                       name="company[newsletter]"
                       value="no"
                       id="newsletter2"
                       checked
                       class="checkbox"/>
                <label for="newsletter2">
                    <?= $block->escapeHtml(__('No')) ?>
                </label>
            </div>
        </div>
        <div class="field is_dba">
                <span class="label">
                    <?= $block->escapeHtml(__('Does your company have a DBA Name?')) ?>
                </span><br role="presentation" /><br role="presentation" />
            <div class="field control radiobtn-inline">
                <input type="radio"
                       name="company[is_dba]"
                       value="yes"
                       id="is_dba1"
                       class="checkbox"/>
                <label for="is_dba1">
                    <?= $block->escapeHtml(__('Yes')) ?>&nbsp;&nbsp;
                </label>
            </div>
            <div class="field control radiobtn-inline">
                <input type="radio"
                       name="company[is_dba]"
                       value="no"
                       id="is_dba2"
                       checked
                       class="checkbox"/>
                <label for="is_dba2">
                    <?= $block->escapeHtml(__('No')) ?>
                </label>
            </div>

        </div>
        <div class="field dba_name" style="display:none;">
            <label class="label" for="dba_name">
                <span><?= $block->escapeHtml(__('DBA Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[dba_name]" id="dba_name" autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field resale_certificate_number">
            <label class="label" for="resale_certificate_number">
                <span><?= $block->escapeHtml(__('Resale Certificate Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[resale_certificate_number]" id="resale_certificate_number"
                       autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field website_address">
            <label class="label" for="website_address">
                <span><?= $block->escapeHtml(__('Website Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[website_address]" id="website_address" autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field social_media_site">
            <label class="label" for="social_media_site">
                <span><?= $block->escapeHtml(__('Social Media Site')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[social_media_site]" id="social_media_site" autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field business_info required">
            <label class="label" for="business_info">
                <span><?= $block->escapeHtml(__('Business Type')) ?></span>
            </label>
            <div class="control _required">
                <select name="company[business_type]" id="business_info"
                        class="select" autocomplete="on"
                        data-validate="{required:true}"
                >
                    <option value=""><?= $block->escapeHtml(__('Select Business Type')) ?></option>
                    <?php $options = $viewModel->getBusinessType(); ?>
                    <?php foreach ($options as $value): ?>
                        <option value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                            <?= $block->escapeHtml($value['label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field no_of_stores">
            <label class="label" for="no_of_stores">
                <span><?= $block->escapeHtml(__('Number of Stores')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[no_of_stores]" id="no_of_stores" autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field sq_ft_per_store">
            <label class="label" for="sq_ft_per_store">
                <span><?= $block->escapeHtml(__('Square Footage per Store')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[sq_ft_per_store]" id="sq_ft_per_store" autocomplete="on"
                       value=""
                       class="input-text">
            </div>
        </div>
        <div class="field type_of_projects">
            <label class="label" for="type_of_projects">
                <span><?= $block->escapeHtml(__('Types of Projects')) ?></span>
            </label>
            <div class="control _required">
                <select name="company[type_of_projects][]" id="type_of_projects"
                        class="select"
                        multiple="multiple">
                    <?php $options = $viewModel->getProjects(); ?>
                    <?php foreach ($options as $option): ?>
                        <optgroup data-type="<?= $block->escapeHtmlAttr($option['type']) ?>" label="<?= $block->escapeHtmlAttr($option['label']) ?>">
                            <?php foreach ($option['value'] as $value): ?>
                                <option value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                                    <?= $block->escapeHtml($value['label']) ?>
                                </option>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field no_of_jobs_per_year">
            <label class="label" for="no_of_jobs_per_year">
                <span><?= $block->escapeHtml(__('Number of Jobs per Year')) ?></span>
            </label>
            <div class="control _required">
                <select name="company[no_of_jobs_per_year]" id="no_of_jobs_per_year"
                        class="select" autocomplete="on"
                >
                    <option value=""><?= $block->escapeHtml(__('Select Number of Jobs per Year')) ?></option>
                    <?php $options = $viewModel->getNumberOfJobsPerYear(); ?>
                    <?php foreach ($options as $value): ?>
                        <option value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                            <?= $block->escapeHtml($value['label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Billing Address')) ?></span></legend>
        <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Street Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][0]" id="street0" autocomplete="address-line1"
                       value=""
                       data-validate="{required:true, maxlength:40}"
                       class="input-text">
            </div>
        </div>
        <div class="field street">
            <label class="label" for="street1">
                <span><?= $block->escapeHtml(__('Street Address 2')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][1]" id="street1" autocomplete="address-line2"
                       value=""
                       class="input-text"
                       data-validate="{maxlength:40}">
            </div>
        </div>
        <div class="field city _required">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[city]" id="city" autocomplete="address-level2"
                       value=""
                       data-validate="{required:true}"
                       class="input-text">
            </div>
        </div>
        <div class="field country_id _required">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $block->getDefaultCountryId(); ?>
                <select name="company[country_id]" id="country_id"
                        class="select" autocomplete="country-name"
                >
                    <option value=""><?= $block->escapeHtml(__('Please select an option.')) ?></option>
                    <?php $countries = $block->getCountriesList(); ?>
                    <?php foreach ($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtmlAttr($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : ''; ?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field region-id required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control _required">
                <?php $message = $block->escapeHtml(__('Please select a region, state or province.')) ?>
                <select name="company[region_id]" id="region_id" class="select" autocomplete="address-level1">
                    <option value=""><?= /* @noEscape */
                        $message ?></option>
                </select>
                <label class="no-display" for="region">
                    <span><?= $block->escapeHtml(__('State/Province')) ?></span>
                </label>
                <input type="text" id="region" name="company[region]"
                       value="" autocomplete="address-level1"
                       class="input-text no-display">
            </div>
        </div>
        <div class="field postcode required">
            <label class="label" for="postcode">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <?php $postcodeClass = $block->escapeHtmlAttr($block->getAttributeValidationClass('postcode')) ?>
                <input type="text" name="company[postcode]" id="postcode"
                       value="" autocomplete="postal-code"
                       class="input-text validate-zip-international <?= /* @noEscape */
                       $postcodeClass ?>"
                       data-validate="{'required':true, 'validate-zip-international':true}"/>
            </div>
        </div>

        <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value="" autocomplete="tel"
                       data-validate="{required:true}"
                       class="input-text">
            </div>
        </div>
        <?php $userAddressAttributes = $block->getLayout()->getBlock('customer_form_address_attributes'); ?>
        <?php if ($userAddressAttributes): ?>
            <?= $userAddressAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif;?>
    </fieldset>

    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Company Administrator')) ?></span></legend>
        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="customer[email]"
                       autocomplete="email"
                       id="email_address"
                       value=""
                       class="input-text"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
"name": "customer_email",
"validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
}}'
                       data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
            </div>
        </div>

        <?= $block->getLayout()->createBlock(Name::class)
            ->setFieldNameFormat('customer[%s]')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>

        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes): ?>
            <?php $userDefinedAttributes->setFieldNameFormat('customer[%1$s]'); ?>
            <?= $userDefinedAttributes->toHtml() ?>
        <?php endif; ?>

        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" >
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

</form>
<script type="text/x-magento-init">
    {
        "*": {
            "perficient_company":{}
        }
    }
</script>

<?php $scriptString = <<<script

    require([
        'jquery',
        'mage/mage'
    ], function($) {

        var dataForm = $('#form-validate');
        var ignore = null;

        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<?php
/** @var DirectoryHelper $directoryDataHelper */
$directoryDataHelper = $block->getData('directoryDataHelper');
$countries = $directoryDataHelper->getCountriesWithOptionalZip(true) ?>
<script type="text/x-magento-init">
    {
        "#country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $directoryDataHelper->getRegionJson() ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $countries ?>
            }
        }
    }
</script>

