<?php
/**
* Inventory for Quickship
* @category: Magento
* @package: Perficient/QuickShip
* @copyright: Copyright 2020 Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
* @license: Magento Enterprise Edition (MEE) license
* @author: Sandeep Mude <Sandeep.mude@perficient.com>
* @keywords: Module Perficient_QuickShip
*/


// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Syspro Order ID #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col ship-to"><?= $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <span><?= $block->escapeHtml($_order->getRealOrderId()) ?></span>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Syspro Order ID #')) ?>" class="col id">
                            <span><?= $block->escapeHtml($_order->getSysproOrderId()) ?></span>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php
                            $shippingAddress = $_order->getShippingAddress();
                            if ($shippingAddress) {
                                $name = $shippingAddress->getFirstname() . ' ' . $shippingAddress->getLastname();
                            } else {
                                $name = $_order->getCustomerName();
                            }
                        ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col ship-to"><?= $block->escapeHtml($name) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view"
                               aria-label="<?= $block->escapeHtml(__('View Order of Order ID')) ?> <?= $block->escapeHtml($_order->getRealOrderId()) ?>" >
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php /*if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId()) && (!$_order->getQuickShip() && ($_order->getSourceFlag() == 1 || $_order->getSourceFlag() == null))) : */?><!--
                                <a href="#" data-post='<?/*= /* @noEscape */
                                /*$this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                */?>'
                                   aria-label="<?/*= $block->escapeHtml(__('Reorder of Order ID')) */?> <?/*= $block->escapeHtml($_order->getRealOrderId()) */?>"
                                   class="action order">
                                    <span><?/*= $block->escapeHtml(__('Reorder')) */?></span>
                                </a>
                            --><?php /*endif */?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
