<?php
/**
* Inventory for Quickship
* @category: Magento
* @package: Perficient/QuickShip
* @copyright: Copyright 2020 Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
* @license: Magento Enterprise Edition (MEE) license
* @author: Sandeep Mude <Sandeep.mude@perficient.com>
* @keywords: Module Perficient_QuickShip
*/

/** @var  $block \Magento\Sales\Block\Order\View*/?>

<?php
$isQuickShip = $escaper->escapeHtmlAttr(__('No'));
if ($block->getOrder()->getQuickShip()) {
$isQuickShip = $escaper->escapeHtmlAttr(__('Yes'));
}
?>
<div class="block-content">
    <dl class="order-quickship">
        <dt class="quickship-label">
            <?= /* @noEscape */
               $escaper->escapeHtmlAttr(__('Quick Ship')) ?>
        </dt>
        <dd class="quickship-content"><?= $isQuickShip ?></dd>
    </dl>
</div>

