<?php
/**
* Inventory for Quickship
* @category: Magento
* @package: Perficient/QuickShip
* @copyright: Copyright 2020 Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
* @license: Magento Enterprise Edition (MEE) license
* @author: Sandeep Mude <Sandeep.mude@perficient.com>
* @keywords: Module Perficient_QuickShip
*/


// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="block block-dashboard-orders">
<?php
    $_orders = $block->getOrders();
    $count = count($_orders);
?>
    <div class="block-title order">
        <h2 class="heading-l2"><?= $block->escapeHtml(__('Recent Orders')) ?></h2>
        <?php if ($count > 0) : ?>
            <a class="action view" aria-label="<?= $block->escapeHtml(__('View All Recent Orders')) ?>" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
    <?= $block->getChildHtml() ?>
    <?php if ($count > 0) : ?>
        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Recent Orders')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Syspro Order ID #')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                        <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                        <th scope="col" class="col quick_ship"><?= $block->escapeHtml(__('Quick Ship')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col actions"><?= $block->escapeHtml(__('Actions')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_orders as $_order) : ?>
                        <tr>
                            <?php $isQuickShip = $_order->getData('quick_ship') ? true : false; ?>
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                                <span><?= $block->escapeHtml($_order->getRealOrderId()) ?></span>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Syspro Order ID #')) ?>" class="col id">
                                <span><?= $block->escapeHtml($_order->getSysproOrderId()) ?></span>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Quick Ship')) ?>" class="col quick_ship"><?= /* @noEscape */ $block->escapeHtml($isQuickShip ?__('Yes'):__('No')) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a aria-label="<?= $block->escapeHtml(__('View Order')) ?> #<?= $block->escapeHtml($_order->getRealOrderId()) ?>" href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                    <span><?= $block->escapeHtml(__('View Order')) ?></span>
                                </a>
                                <?php /*if ($this->helper(\Magento\Sales\Helper\Reorder::class)
                                        ->canReorder($_order->getEntityId()) && (!$isQuickShip && ($_order->getSourceFlag() == 1 || $_order->getSourceFlag() == null))): */?><!--
                                    <a href="#" aria-label="<?/*= $block->escapeHtml(__('Reorder')) */?> #<?/*= $block->escapeHtml($_order->getRealOrderId()) */?>" data-post='<?/*= /* @noEscape */
                                    /*$this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    */?>' class="action order">
                                        <span><?/*= $block->escapeHtml(__('Reorder')) */?></span>
                                    </a>
                                --><?php /*endif */?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
    <?php endif; ?>
    </div>
</div>
