<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$buyRequest = $_item->getBuyRequest()->getData();
$viewModel = $block->getViewModel();
$productimizeHelper = $viewModel->getProductimizeHelper();
$giftMessageHelper = $viewModel->getGiftMessageHelper();
$imageUrl = $productimizeHelper->getImageurlfrombuyrequestdata($buyRequest);
?>
<tr>
    <td style="display: flex" class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
        <dl class="item-options" style="display: grid; grid-template-columns: auto auto;">
            <?php foreach ($block->getItemOptions() as $option) : ?>
            <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
            <dd>
                <?php if($option['label'] == 'CustomImage'): ?>
                <a target="_blank" href="<?=$option['value']?>"><?=basename($option['value'])?></a>
                <?php else: ?>
                <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
        <?php if($imageUrl != ''): ?>
        <img style="display: block;height: 200px; width: 200px;object-fit: contain;" src="<?=$imageUrl?>" />
        <?php endif; ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
&& $_giftMessage = $giftMessageHelper->getGiftMessage($_item->getGiftMessageId())
) : ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
