<?php
$actionUrl = $block->getActionUrlimgdisassociate();
?>
<div class="import-shipping">
  <div class="header">
    <h4>CSV File:</h4>
  </div>
  <form class="import-shipping-form" action="<?php echo $actionUrl?>" method="POST" enctype="multipart/form-data">
   <input name="form_key" type="hidden" value="<?=$block->getFormKey()?>">
    <input type="file" required class="required-entry" name="csv" />
    <button type="submit">Import</button>
  </form>
</div>