<?php
/**
 * @author     DCKAP <extensions@dckap.com>
 * @package    DCKAP_Productimize
 * @copyright  Copyright (c) 2017 DCKAP Inc (http://www.dckap.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$siteUrl = $this->getSiteUrl();
?>
<table style="margin-left: -145px; width: 445px;">
    <tr>
        <td style="text-align: right;"><b>Site Url</b></td>
        <td><input type="text" class="productmize_ccsite_url" id="productmize_ccsite_url" name="productmize_ccsite_url" value="<?php echo $siteUrl; ?>" /></td>
    </tr>
</table>