<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Perficient\Order\Block\Item\Renderer */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Wendover\Theme\ViewModel\WendoverViewModel $viewModel */

use Perficient\Catalog\Helper\Data as CatalogHelper;

$_item = $block->getItem();
$product = $_item->getProduct();
$productUrl = $product->getUrlModel()->getUrl($product);
$viewModel = $block->getData('wendover_model');
/** @var CatalogHelper $catalogHelper */
$catalogHelper = $this->helper(CatalogHelper::class);
?>
<?php
$imageUrl = '';
$customizedDataArray = [];
if($_item->getBuyRequest() !== null) {
    $buyRequest = $_item->getBuyRequest()->getData();
    $imageUrl = $viewModel->getImageUrlFromBuyRequestData($buyRequest);
    $infoBuyRequest  = $_item->getBuyRequest()->getData();
    if(!empty($infoBuyRequest) && isset($infoBuyRequest['edit_id'])) {
        $customizeEditId = $infoBuyRequest['edit_id'];
    }
    $expectedProductLabels = null;
    if ($viewModel?->isMirrorProduct($product)) {
        $expectedProductLabels = CatalogHelper::$expectedConfMirrorProductLabel;
    }

    if(isset($buyRequest['pz_cart_properties']) && $buyRequest['pz_cart_properties']) {
        $customizedDataArray = $viewModel->getValidCustomizedOptions(
            $buyRequest['pz_cart_properties'], $expectedProductLabels
        );
    }
}
$productName = $_item->getName();
$imgUrl = $viewModel->getImageURL($product, 'product_thumbnail_image');
if($viewModel->isMirrorProduct($product)) {
    $productData = $catalogHelper->getProductBySku($block->getSku());
    $productUrl = $catalogHelper->getMirrorProductUrl($productData->getId());
    $productName = $viewModel->getProductName($productData);
    $imgUrl = $viewModel->getImageURL($productData, 'product_thumbnail_image');
}


$miscSku = strtolower($block->getSku());
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>">
    <div class="order-detail-name">
        <?php if($miscSku == "misc"):?>
            <strong class="product name product-item-name">
                <?= $escaper->escapeHtml($productName) ?>
            </strong>
        <?php else : ?>
            <a href="<?= $escaper->escapeUrl($productUrl) ?>">
                <strong class="product name product-item-name">
                    <?= $escaper->escapeHtml($productName) ?>
                </strong>
            </a>
        <?php  endif; if (isset($customizeEditId)) :?>
            <img src="<?= $block->getViewFileUrl('Perficient_Order/images/icon.palette.svg'); ?>" alt="" style="padding-left: 10px;vertical-align: middle;" />
            <span class="customized-name" style="margin-left: 1rem;"><?= $block->escapeHtml(__('Customized')) ?></span>
        <?php endif; ?>
        </div>
        <?php if (!empty($customizedDataArray['dataArray'])) : ?>
            <dl class="item-options">
                <?php foreach ($customizedDataArray['dataArray'] as $labelKey => $labelValue) :?>
                    <dt><?= $block->escapeHtml($labelKey) ?></dt>
                    <dd>
                        <?= $labelValue ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php elseif ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <?php
                        // Condition for weighted Mats - Removed the tooltip class
                        if (isset($_formatedOptionValue['full_view']) && (strpos(strtolower($block->stripTags($_option['value'])), 'weighted') !== false)): ?>
                            <dd>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a', 'img','span', 'i']) ?>
                            </dd>
                        <?php else: ?>
                            <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                                <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                                            <dd><?= $escaper->escapeHtml($_formatedOptionValue['full_view'],['span', 'i']) ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd><?= $escaper->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>

            </dl>
        <?php endif; ?>
        <?php if($imageUrl != ''): ?>
            <img width="100" height="100" style="display: block;" src="<?=$imageUrl?>" alt="" />
        <?php else:
            ?>
            <img width="100" height="100" style="display: block;" src="<?=$imgUrl?>" alt="" />
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>

    </td>
    <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <div class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
                </div>
            <?php endif; ?>
        </div>
    </td>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
