<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<button data-ammenu-js="menu-toggle" aria-label="<?= $escaper->escapeHtml(__('Toggle Button')) ?>"
      class="ammenu-menu-toggle<?= /* @noEscape */ $block->isHamburgerEnabled() ? ' -hamburger' : '' ?><?= /* @noEscape */ $block->getData('is_porto') ? ' -porto' : '' ?>"
>
    <span class="ammenu-icon"></span>
    <span class="ammenu-icon"></span>
    <span class="ammenu-icon"></span>
</button>
