<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
$item = $block->getItem();
$product = $item->getProduct();
?>
<a href="#"
   aria-label="<?= $block->escapeHtml(__('Remove item')) ?> <?= $block->escapeHtml($product->getName()) ?>"
   class="action action-delete"
   data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>