<?php
/**
 * Price Multiplier
 *
 * @category: PHP
 * @package: Perficient/PriceMultiplier
 * @copyright: Copyright  2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Sandeep Mude <sandeep.mude@perficient.com>
 * @keywords: Module Perficient_PriceMultiplier
 */
?>
<div id="storeCatalogUrl" data-bind="scope:'storeCatalogUrl'" style="display: none;">
    <script>
        window.storeCatalogUrl = <?php /* @escapeNotVerified */ echo json_encode($block->getConfig()); ?>;
    </script>
</div>
