<?php
/**
 * Added to handle product surcharge if minimum order amount not met by customer
 * @category: Magento
 * @package: Perficient/Order
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Sachin Badase <Sachin.Badase@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_Order
 */

use Magento\Checkout\Block\Cart\Item\Renderer as CartItemRenderer;
use Magento\Framework\Escaper;
use Perficient\Catalog\Helper\Data as CatalogHelper;
use Wendover\Theme\ViewModel\WendoverViewModel;

/**
 * @var $block CartItemRenderer
 * @var $escaper Escaper
 * @var $viewModel WendoverViewModel
 */
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$viewModel = $block->getData('wendover_model');
$canApplyMsrp = $viewModel->getBeforeOrderConfirm($product) && $viewModel->getMinimalPriceLessMsrp($product);
$surchargeSku = $viewModel->getSurchargeProductSku();
$infoBuyRequest = $_item->getOptionByCode('info_buyRequest');
$customizeEditId = $viewModel->getCustomizeEditId($infoBuyRequest);
$productConfiguration = $viewModel->getPzCartProperties($infoBuyRequest);
$productUrl = ($customizeEditId ?
    $viewModel->getEditUrl($block->getProductUrl(), $customizeEditId) :
    $viewModel->getProductUrl($product)
);
$productName = $viewModel->getProductName($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) : ?>
            <div tabindex="-1"
                class="product-item-photo">
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            </div>
        <?php else : ?>
            <span class="product-item-photo">
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $escaper->escapeUrl($productUrl) ?>"><?= $escaper->escapeHtml($productName) ?></a>
                <?php else :?>
                    <?= $escaper->escapeHtml($productName) ?>
                <?php endif; ?>
            </strong>
            <?php if ($customizeEditId) :?>
                <img class="customized-img" src="<?= $block->getViewFileUrl('Perficient_Order/images/icon.palette.svg'); ?>" alt="">
                <span class="customized-name"><?= $escaper->escapeHtml(__('Customized')) ?></span>
            <?php endif; ?>
            <?php if ($productConfiguration) :?>
            <?php $expectedProductLabels = null;
                if ($viewModel->isMirrorProduct($_item->getProduct())) {
                    $expectedProductLabels = CatalogHelper::$expectedConfMirrorProductLabel;
                }
                $cartConfig = $viewModel->getValidCustomizedOptions($productConfiguration, $expectedProductLabels); ?>
            <?php $data = $cartConfig['dataArray'];
                if(!empty($data)): ?>
                <dl class="item-options">
                    <!--To show sku on cart page-->
                    <?php if(!empty($_item->getSku())): ?>
                    <dt><?= $escaper->escapeHtml('Sku') ?></dt>
                    <dd><?= $escaper->escapeHtmlAttr($_item->getSku()) ?></dd>
                    <?php endif; ?>
                    <?php foreach ($data as $labelKey => $labelValue) :?>
                        <dt><?= $escaper->escapeHtml($labelKey) ?></dt>
                        <dd>
                            <?= $labelValue ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
                <?php endif; ?>
            <?php elseif ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <!--To show sku on cart page-->
                    <?php if(!empty($_item->getSku())): ?>
                        <dt><?= $escaper->escapeHtml('Sku') ?></dt>
                        <dd><?= $escaper->escapeHtmlAttr($_item->getSku()) ?></dd>
                    <?php endif; ?>
                    <?php foreach ($_options as $_option) :?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                <?= $escaper->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a', 'i']) ?>
                            <?php else :?>
                                <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['span', 'a', 'i']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $escaper->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($escaper->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $escaper->escapeJs($escaper->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $escaper->escapeJs($escaper->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else :?>
        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <?php if($surchargeSku != $product->getSku()): ?>
        <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                        <input id="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $escaper->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </label>
                </div>
            </div>
        </td>
    <?php else: ?>
        <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                        <input type="hidden" for="cart-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-qty">
                    </label>

                </div>
            </div>
        </td>
    <?php endif; ?>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<?php if($surchargeSku != $product->getSku()): ?>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
<?php endif; ?>
</tbody>
