<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Perficient\Wishlist\Block\Customer\Wishlist\Button\Collaborate $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()) : ?>
    <button type="submit" name="save_and_collaborate" class="action collaborate">
        <span><?= $escaper->escapeHtml(__('Collaborate')) ?></span>
    </button>
<?php endif;?>
