<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <h2 class="heading-l2"><?= $block->escapeHtml(__('Order Information')) ?></h2>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()) : ?>
            <?php
            $shippingAdd = $_order->getShippingAddress();
            if (isset($shippingAdd)) : ?>
            <div class="box box-order-shipping-address">
                <h3 class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></h3>
                <div class="box-content">
                    <address>
                        <?= strip_tags($block->getFormattedAddress($_order->getShippingAddress()),"<br>") ?>
                    </address>
                </div>
            </div>
            <?php endif; ?>
            <div class="box box-order-shipping-method">
                <h3 class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </h3>
                <div class="box-content">
                <?php if ($_order->getShippingDescription()) : ?>
                    <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                <?php else : ?>
                    <?= $block->escapeHtml(__('No shipping information available')) ?>
                <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <?php
        $billingAdd = $_order->getBillingAddress();
        if (isset($billingAdd)) : ?>
        <div class="box box-order-billing-address">
            <h3 class="box-title">
                <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
            </h3>
            <div class="box-content">

                <address>
                    <?= strip_tags($block->getFormattedAddress($_order->getBillingAddress()),"<br>") ?>
                </address>

            </div>
        </div>
        <?php endif; ?>

        <div class="box box-order-billing-method">
            <h3 class="box-title">
                <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
            </h3>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
