<?php
/** @var Perficient\Base\Block\GetData $block */
?>
<head>
       <title>URL Rewrite Import</title>
</head>
<div class="import-url-rewrite">
  <div class="header">
    <h4>CSV File:</h4>
  </div>
  <form class="import-url-rewrite" action="<?= $block->getFormUrl()?>" method="POST" enctype="multipart/form-data">
   <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>">
    <input type="file" required class="required-entry" name="csv" />
    <button type="submit">Import</button>
  </form>
</div>
