<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem() ?>
<?php
$buyRequest = $_item->getBuyRequest()->getData();
$viewModel = $block->getViewModel();
$productimizeHelper = $viewModel->getProductimizeHelper();
$imageUrl = $productimizeHelper->getImageurlfrombuyrequestdata($buyRequest);
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?php if($option['label'] == 'CustomImage'): ?>
                            <a target="_blank" href="<?=$option['value']?>"><?=basename($option['value'])?></a>
                        <?php else: ?>
                            <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                        <?php endif; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
        <?php if($imageUrl != ''): ?>
            <img width="140" height="140" style="display: block" src="<?=$imageUrl?>" />
        <?php endif; ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQty() ?></td>
</tr>
