<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<div class="block block-addresses-default">
    <h2 class="block-title"><strong><?= $block->escapeHtml(__('Default Addresses')) ?></strong></h2>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getDefaultBilling()) : ?>
            <div class="box box-address-billing">
                <h3 class="box-title heading-l3">
                    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
                </h3>
                <div class="box-content">
                    <address>
                        <?= strip_tags($block->getAddressHtml($block->getAddressById($_pAddsses)),"<br>") ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span><?= $block->escapeHtml(__('Change Billing Address')) ?></span>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="box box-billing-address">
                <h3 class="box-title heading-l3"><span><?= $block->escapeHtml(__('Default Billing Address')) ?></span></h3>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultShipping()) : ?>
            <div class="box box-address-shipping">
                <h3 class="box-title heading-l3">
                    <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
                </h3>
                <div class="box-content">
                    <address>
                        <?= strip_tags($block->getAddressHtml($block->getAddressById($_pAddsses)),"<br>") ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span><?= $block->escapeHtml(__('Change Shipping Address')) ?></span>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="box box-shipping-address">
                <h3 class="box-title heading-l3"><span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span></h3>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
