<?php
/**
 * This module is used to add product attribute in page
 * @category: Magento
 * @package: Perficient/magento Wishlist
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: harshal dantalwar <harshal.dantalwar@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient Wishlist

 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info as WishlistItemInfo;
use Magento\Wishlist\Model\Item as ItemModel;
use Perficient\Catalog\Helper\Data as CatalogHelper;

/** @var WishlistItemInfo $block */
/** @var ItemModel $item */
/** @var Escaper $escaper */
/** @var CatalogHelper $catalogHelper */
$catalogHelper = $this->helper(CatalogHelper::class);
$item = $block->getItem();
$product = $block->getProduct();
$buyRequest = $item->getBuyRequest();
$productimizeEditId = $buyRequest->getEditId();
$productConfiguration = $buyRequest->getPzCartProperties();
?>
    <strong class="product-item-name">
        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" class="product-item-link">
            <?= $block->escapeHtml($product->getName()) ?>
            <?php if($productimizeEditId): ?>
                <div class="pz-customize-color">
                    <img data-bind="attr: { src: require.toUrl('DCKAP_Productimize/images/icon.palette.svg') }"  />
                    <span class="pz-customize-color-text">Customized</span>
                </div>
            <?php endif; ?>
        </a>
    </strong>
<?php
if ($productConfiguration) {
    //$confData = $catalogHelper->getDefaultConfigurationValidJson($productConfiguration);
    $expectedProductLabels = null;
    if ($catalogHelper->isMirrorProduct($item->getProduct())) {
        $expectedProductLabels = $catalogHelper::$expectedConfMirrorProductLabel;
    }
    $confData = $catalogHelper->getValidCustomizedOptions($productConfiguration, false, $expectedProductLabels);
    $data = $confData['dataArray'];
    if(!empty($data)){
        ?>
        <div class="attribute-section">
            <ul role="list">
                <!--To show sku on Project Pages -->
                <?php if(!empty($product->getSku())): ?>
                <li role="listitem">
                    <span class="title"><?= $escaper->escapeHtml('Sku') ?>: </span>
                    <span class="value"><?= $escaper->escapeHtml($product->getSku()) ?></span>
                </li>
                <?php endif; ?>
                <?php foreach($data as $labelKey => $labelValue) { ?>
                    <?php if($productimizeEditId && $labelKey == 'CustomImage'): continue; endif; ?>
                    <li role="listitem">
                        <span class="title"><?= $escaper->escapeHtml($labelKey) ?>: </span>
                        <?php if($productimizeEditId){ ?>
                            <span class="value"><?= $escaper->escapeHtml($labelValue,['span', 'i']) ?></span>
                        <?php } else{ ?>
                            <span class="value"><?= $labelValue ?></span>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php }} ?>
