<?php
/**
 * RequisitionList Converted to Market Scans with project specific configurations
 * @copyright: Copyright © 2020 Perficient, Inc. All rights reserved.
 * @license: Perficient, Inc.
 * @author: Sachin Badase <sachin.badase@perficient.com>
 * @project: Wendover
 * @keywords:  Module Perficient_RequisitionList
 */

/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="requisition-toolbar">
    <div class="requisition-toolbar-select">
        <input type="checkbox" name="requisition-select-all" id="requisition-select-all" data-role="select-all" />
        <label class="label" for="requisition-select-all"><?= $block->escapeHtml(__('Select all')) ?></label>
    </div>
</div>
