<?php
/**
 *
 * This file used to remove title(WCAG Changes)
 *
 * @category: Magento
 * @package: Perficient/Shipping
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Shipping remove title
 */

?>
<?php /** @var $block \Magento\Shipping\Block\Tracking\Link */ ?>
<?php $order = $block->getOrder() ?>
<a href="#" class="action track"
   data-mage-init='{"popupWindow": {
        "windowURL":"<?= $block->escapeUrl($block->getWindowUrl($order)) ?>",
        "windowName":"trackorder",
        "width":800,
        "height":600,
        "left":0,
        "top":0,
        "resizable":1,
        "scrollbars":1
    }}'>
    <span><?= $block->escapeHtml($block->getLabel()) ?></span>
</a>
