<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$buyRequest = $_item->getBuyRequest()->getData();
$viewModel = $block->getViewModel();
$productimizeHelper = $viewModel->getProductimizeHelper();
$catalogHelper = $viewModel->getCatalogImage();
$imageUrl = $productimizeHelper->getImageurlfrombuyrequestdata($buyRequest);
$product = $block->getItem()->getProduct();
if(!empty($buyRequest) && isset($buyRequest['edit_id'])) {
    $customizeEditId = $buyRequest['edit_id'];
}
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>" >
        <strong class="product name product-item-name">
            <?= $block->escapeHtml($_item->getName()) ?>
            <?php if (isset($customizeEditId)) :?>
                <img src="<?= $block->getViewFileUrl('Perficient_Order/images/icon.palette.svg'); ?>" alt="Customizable Product" style="padding-left: 10px;vertical-align: middle;" />
                <span class="customized-name" style="margin-left: 1rem;"><?= $block->escapeHtml(__('Customized')) ?></span>
            <?php endif; ?>
        </strong>
        <?php if($imageUrl != ''): ?>
        <!-- <div class="productimize_added_element_container_myaccount"> -->
            <?php endif; ?>
            <?php if ($_options = $block->getItemOptions()) : ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>

                            <?php
                            $matValues = array("Top Mat","Bottom Mat","Frame");
                            if(in_array($_option['label'], $matValues) && (isset($_formatedOptionValue['full_view']))): ?>
                                <dd><?= $block->stripTags((isset($_option['print_value']) ? str_replace(' Weighted',', ',$_option['print_value']) : str_replace(' Weighted',', ',$_option['value']))) ?></dd>
                            <?php else: ?>
                                <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                                    <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                        <div class="tooltip content">
                                            <dl class="item options">
                                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                                <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                            </dl>
                                        </div>
                                    <?php endif; ?>
                                </dd>
                            <?php endif; ?>
                        <?php else : ?>
                            <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>                
            <?php endif; ?>            
            <?php if($imageUrl != ''): ?>         
            <img width="100" height="100" style="display: block;" src="<?=$imageUrl?>" />
        <!-- </div> -->
        <?php else:
        $imgUrl = $catalogHelper->init($product, 'product_thumbnail_image')
        ->constrainOnly(TRUE)
        ->keepAspectRatio(TRUE)
        ->keepTransparency(TRUE)
        ->keepFrame(FALSE)
        ->resize(100, 100)->getUrl();
        ?>
        <img width="100" height="100" style="display: block;" src="<?=$imgUrl?>" alt="" />    
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
