<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Company\Block\Company\Account\Dashboard\RoleInfo $block
 * @var \Magento\Framework\Escaper $escaper
 */
$customerRoles = $block->getCustomerRoles();
$array_label = ["Company Employee", "Invited Customer", "Invited Customer"];
$array_role =  ["Customer Employee", "Customer's Customer", "Customer039s Customer"];
?>
<?php if ($customerRoles): ?>
    <div class="box box-role">
        <strong class="box-title">
        <span><?= (count($customerRoles) == 1) ?
                $escaper->escapeHtml(__('User Role')) :
                $escaper->escapeHtml(__('User Roles')) ?></span>
        </strong>
        <div class="box-content">
            <p class="company-roles">
                <?php foreach ($customerRoles as $role):
                    $role =  preg_replace('/[^a-zA-Z0-9_ -]/s','',$escaper->escapeHtml($role));?>
                    <span><?= str_replace($array_role, $array_label,$role); ?></span>
                <?php endforeach; ?>
            </p>
        </div>
    </div>
<?php endif; ?>
