<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Base for Magento 2
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Amasty\Xsearch\ViewModel\FormMiniData $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getViewModel();
$options = $viewModel->getOptions();
$isBaseSearch = $block->getNameInLayout() === 'top.search';
$wrapperId = $isBaseSearch ? 'amsearch_wrapper' : 'amsearch_wrapper_' . uniqid();
$colorSettings = $viewModel->getColorSettings();
?>
<button class="openBtn" aria-label="Search"><span>Open Search Box</span></button>

<section class="amsearch-wrapper-block block-search overlay" data-amsearch-wrapper="block" data-bind="
            scope: '<?= /* @noEscape */ $wrapperId ?>',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        <?= /* @noEscape */ $wrapperId ?>: {
                            component: 'Amasty_Xsearch/js/wrapper',
                            data: <?= $escaper->escapeHtml($options) ?>
                        }
                    }
                }
            }">
    <?php if ($viewModel->isFullScreenEnabled()) : ?>
        <button class="amsearch-button -full-close closebtn action-close" data-bind="
                    event: {
                        click: close
                    },
                    visible: opened">
        </button>
    <?php endif; ?>
    <div class="block block-title"><strong>What can we help you find today?</strong></div>
    <div class="amsearch-form-block overlay-content" data-bind="
              style: {
                    width: resized() ? data.width + 'px' : ''
              },
              css: {
                '-opened': opened
              },
              afterRender: initCssVariables">
        <?php if ($viewModel->isFullScreenEnabled() && $isBaseSearch) : ?>
            <label class="amsearch-full_width-title" data-bind="i18n: 'Search'"></label>
        <?php endif; ?>
        <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Amasty_Xsearch::search/input.phtml')) ?>
        <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Amasty_Xsearch::components/search_button.phtml')) ?>
        <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Amasty_Xsearch::components/results.phtml')) ?>
    </div>
    <button class="closebtn action-close" id="closebtn" data-role="closeBtn" type="button"><span>Close</span></button>

</section>
