<?php
/**
 * File to create left bar.
 *
 * @category: PHP HTML
 * @package: Perficient/MyCatalog
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Suhas Dhoke <Suhas.Dhoke@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_MyCatalog
 */

// @codingStandardsIgnoreFile
/** @var $block \Perficient\MyCatalog\Block\MyPages */
?>
<form class="form popup-catalog-form" id="new_catalog_form" name="new_catalog_form" method="POST" action="<?php echo $block->getUrl('mycatalog/index/edit/');?>" data-mage-init='{"validation":{}}' enctype="multipart/form-data">
    <ul style="overflow: hidden; display: block;">
    <?php for ($i = 1; $i <= 8; $i++): ?>
        <li class="catalog-template" onclick="updateSelectedTemplateId(<?= $i; ?>)">
            <a class="dd-option" tabindex="0">
                <fieldset>
                    <legend class="no-display">Option Catalog Form </legend>
                    <input tabindex="-1" class="dd-option-value" name="select-template" id="frame-template_<?= $i; ?>" type="radio" value="<?= $i; ?>">
                    <img
                            class="dd-option-image dd-option-template-image"
                            data-id="<?= $i; ?>"
                            alt="layout-page-img<?= $i; ?>"
                            src="<?= $block->getViewFileUrl('Perficient_MyCatalog/images/' . $i . '.png') ?>"
                            id="layout_page_<?= $i; ?>"
                    />
                    <label class="dd-option-text" for="frame-template_<?= $i; ?>"><?= __('FRONT COVER'); ?></label>
                </fieldset>
            </a>
        </li>
    <?php endfor; ?>

</ul>
    <?php
    /**
     * File to create new catalog.
     * @category: PHP HTML
     * @package: Perficient/MyCatalog
     * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     * @license: Magento Enterprise Edition (MEE) license
     * @author: Suhas Dhoke <Suhas.Dhoke@Perficient.com>
     * @project: Wendover
     * @keywords: Module Perficient_MyCatalog
     */

    // @codingStandardsIgnoreFile
    /** @var $block \Perficient\MyCatalog\Block\MyCatalog */
    ?>
    <?php $catalogData = $block->getCatalogData(); ?>
    <div class="new-catalog">
            <fieldset class="fieldset">
                <legend class="no-display"><span><?= __('FRONT COVER'); ?></span></legend>
                <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey()?>" />
                <input name="wishlist_id" type="hidden" value="<?= /* @noEscape */ $catalogData['wishlist_id']; ?>" />
                <input name="catalog_id" type="hidden" value="<?= /* @noEscape */ $catalogData['catalog_id']; ?>" />
                <input type="hidden" name="logo_image" id="wendover_logo" value="<?= /* @noEscape */ $catalogData['logo_image']; ?>" />
                <input type="hidden" name="page_template_id" id="page_template_id" value="1">
                <input type="hidden" name="get_pdf" id="get_pdf" value="0">
                <div id="new-catalog-front-page" class="catalog-front-page-section">
                    <h3 class="legend page-title"><span><?= __('FRONT COVER'); ?></span></h3>
                    <div class="front-page-inner-container">
                        <div class="field catalog_logo">
                            <div class="mycatalog_placeholder" >
                                <?php if (!empty($catalogData['logo_image']) && !empty($catalogData['logo_image_url'])): ?>
                                    <img src="<?= $catalogData['logo_image_url']; ?>" height="100%" alt="<?= __('Cover Logo'); ?>" />
                                <?php else: ?>
                                    <div><?= __('LOGO'); ?></div>
                                <?php endif; ?>
                            </div>
                            <label class="label hide" for="catalog_logo"><span><?php /* @escapeNotVerified */ echo __('Logo') ?></span></label>
                            <div class="control">
                                <input name="logo" id="catalog_logo" type="file" />
                            </div>
                        </div>
                        <div class="field catalog_title required">
                            <label class="label hide" for="catalog_title">
                                <span><?= /* @escapeNotVerified */ __('Catalog Title'); ?></span>
                            </label>
                            <input name="catalog_title"
                                   id="catalog_title"
                                   aria-required="true"
                                   type="text"
                                   autocomplete="on"
                                   class="required"
                                   data-validate="{required:true}"
                                   placeholder="<?= /* @escapeNotVerified */ __('Catalog Title') ?>"
                                   value="<?= (strlen($catalogData['catalog_title']) > 0) ? $catalogData['catalog_title'] : $block->getDefaultCatalogTitle() ?>"/>
                        </div>
                        <div class="field additional_info_1">
                            <label class="label hide" for="additional_info_1">
                                <span><?= /* @escapeNotVerified */ __('Additional Information Line 1'); ?></span>
                            </label>
                            <input name="additional_info_1"
                                   id="additional_info_1"
                                   type="text"
                                   autocomplete="on"
                                   placeholder="<?= /* @escapeNotVerified */ __('Additional Information Line 1') ?>"
                                   value="<?= $catalogData['additional_info_1']; ?>" />
                        </div>
                        <div class="field additional_info_2">
                            <label class="label hide" for="additional_info_2">
                                <span><?= /* @escapeNotVerified */ __('Additional Information Line 2'); ?></span>
                            </label>
                            <input name="additional_info_2"
                                   id="additional_info_2"
                                   type="text"
                                   autocomplete="on"
                                   placeholder="<?= /* @escapeNotVerified */ __('Additional Information Line 2') ?>"
                                   value="<?= $catalogData['additional_info_2']; ?>" />
                        </div>
                    </div>
                </div>

                <div id="new-catalog-back-page" class="catalog-back-page-section">
                    <h3 class="legend page-title"><span><?= __('BACK COVER'); ?></span></h3>
                    <div class="back-page-inner-container">
                        <div class="field name">
                            <label class="label hide" for="name">
                                <span><?= /* @escapeNotVerified */ __('Name'); ?></span>
                            </label>
                            <input name="name"
                                   id="name"
                                   type="text"
                                   autocomplete="given-name"
                                   placeholder="<?= /* @escapeNotVerified */ __('Name') ?>"
                                   value="<?php if(strlen($catalogData['name']) > 0):
                                       echo $catalogData['name'];
                                   else:
                                       echo $block->getCustomerName();
                                   endif; ?>" />
                        </div>
                        <div class="field phone_number">
                            <label class="label hide" for="phone_number">
                                <span><?= /* @escapeNotVerified */ __('Phone'); ?></span>
                            </label>
                            <input name="phone_number"
                                   id="phone_number"
                                   type="text"
                                   autocomplete="tel"
                                   placeholder="<?= /* @escapeNotVerified */ __('Phone') ?>"
                                   value="<?php if(strlen($catalogData['phone_number']) > 0):
                                       echo $catalogData['phone_number'];
                                   else:
                                       echo $block->getCustomerPhoneNumber();
                                   endif; ?>" />
                        </div>
                        <div class="field website_url">
                            <label class="label hide" for="website_url">
                                <span><?= /* @escapeNotVerified */ __('Website URL'); ?></span>
                            </label>
                            <input name="website_url"
                                   id="website_url"
                                   type="text"
                                   autocomplete="url"
                                   placeholder="<?= /* @escapeNotVerified */ __('Website URL') ?>"
                                   value="<?php if($catalogData['website_url']):
                                       echo $catalogData['website_url'];
                                   else:
                                       echo $block->getCustomerWebsite();
                                   endif; ?>" />
                        </div>
                        <div class="field company_name">
                            <label class="label hide" for="company_name">
                                <span><?= /* @escapeNotVerified */ __('Company Name'); ?></span>
                            </label>
                            <input name="company_name"
                                   id="company_name"
                                   autocomplete="organization"
                                   type="text"
                                   placeholder="<?= /* @escapeNotVerified */ __('Company Name') ?>"
                                   value="<?php if($catalogData['company_name']):
                                       echo $catalogData['company_name'];
                                   else:
                                       echo $block->getCustomerCompanyName();
                                   endif; ?>" />
                        </div>
                    </div>
                </div>

                <div class="action btn-container">
                    <button class="action primary" type="submit" onclick="createPdf();" value="continue" name="continue">
                        <span><?= /* @escapeNotVerified */ __('Create Catalog') ?></span>
                    </button>
                    <button class="action primary" type="submit"  onclick="editPdf();"  value="continue" name="continue">
                        <span><?= /* @escapeNotVerified */ __('View/Edit') ?></span>
                    </button>
                          </div>
            </fieldset>
        </form>
    </div>
    <script type="text/x-magento-init">
{
    "*" : {
        "wendoverJS": {}
    }
}
</script>
    <script>
        var mediaUrl = '<?php echo $block->getMediaUrl(); ?>';
    </script>

<script>
    function updateSelectedTemplateId(selectedValue){
        document.getElementById("page_template_id").value = selectedValue;
    }
    function createPdf(){
        document.getElementById("get_pdf").value = 1;
    }

    function editPdf(){
        document.getElementById("get_pdf").value = 0;
    }
</script>
