<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Perficient\Catalog\Helper\Data as CatalogHelper;
use Wendover\Theme\ViewModel\WendoverViewModel;
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Perficient\Order\Block\Email\Items\ItemRenderer */

/** @var $_item \Magento\Sales\Model\Order\Item
 * @var $viewModel WendoverViewModel
 * */
$_item = $block->getItem();
$_order = $_item->getOrder();
$buyRequest = $_item->getBuyRequest()->getData();
$productimizeHelper = $this->helper(\DCKAP\Productimize\Helper\Data::class);
$imageUrl = $productimizeHelper->getImageurlfrombuyrequestdata($buyRequest);
/**
 * Lead Time Notification.
 */
$leadTime = '';
$customizedDataArray = [];
$options = $_item->getProductOptions();
$viewModel = $block->getData('wendover_model');
$expectedProductLabels = null;
if ($viewModel->isMirrorProduct($_item->getProduct())) {
    $expectedProductLabels = CatalogHelper::$expectedConfMirrorProductLabel;
}
if (!empty($options['info_buyRequest']) && !empty($options['info_buyRequest']['lead_time'])) {
    $leadTime = $options['info_buyRequest']['lead_time'];
}
if (!empty($options['info_buyRequest']) && isset($options['info_buyRequest']['edit_id'])) {
    $customizeEditId = $options['info_buyRequest']['edit_id'];
}
$catalogHelper = $this->helper('Perficient\Catalog\Helper\Data');
if(isset($buyRequest['pz_cart_properties']) && $buyRequest['pz_cart_properties']) {
    $customizedDataArray = $catalogHelper->getValidCustomizedOptions($buyRequest['pz_cart_properties'], false, $expectedProductLabels);
}
$product = $_item->getProduct();
$productName = $_item->getName();
if($viewModel->isMirrorProduct($product)) {
    $productData = $catalogHelper->getProductBySku($block->getSku($_item));
    $productName = $viewModel->getProductName($productData);
    $imageUrl =  $viewModel->getImageURL($productData, 'product_thumbnail_image');
}
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name">
            <?= $block->escapeHtml($productName) ?>
            <?php if (isset($customizeEditId)) :?>
                <span class="customized-name" style="margin-left: 1rem;"><?= $block->escapeHtml(__('Customized')) ?></span>
            <?php endif; ?>
        </p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if (!empty($customizedDataArray['dataArray'])) : ?>
            <dl class="item-options">
                <?php foreach ($customizedDataArray['dataArray'] as $labelKey => $labelValue) :?>
                    <dt><?= $block->escapeHtml($labelKey) ?></dt>
                    <dd>
                        <?= $labelValue ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php elseif ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?php if($option['label'] == 'CustomImage'): ?>
                            <a target="_blank" href="<?=$option['value']?>"><?=basename($option['value'])?></a>
                        <?php else: ?>
                            <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                        <?php endif; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>

        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
        <?php if($imageUrl != ''): ?>
            <img style="display: block;height: 200px; width: 200px;object-fit: contain;" src="<?=$imageUrl?>" />
        <?php else: ?>
            <?= $block->getProductImage($_item,'cart_page_product_thumbnail')->toHtml() ?>
        <?php endif; ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if (!empty($leadTime)): ?>
    <tr class="lead-time-msg">
        <td colspan="3">
            <span class="lead_time"><?= __($leadTime); ?></span>
        </td>
    </tr>
<?php endif; ?>

<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
