<?php
/**
 * File to create/update artwork catalog.
 * @category: PHP HTML
 * @package: Perficient/MyCatalog
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Suhas Dhoke <Suhas.Dhoke@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_MyCatalog
 */

// @codingStandardsIgnoreFile
/** @var $block \Perficient\MyCatalog\Block\MyPages */
?>
<?php
$templateData = $this->getData('templateData');
$images = $templateData['images'];
$data   = $templateData['data'];
?>
<!--  Four quarters grid -->

<div id="wendover_template1" class="wendover_template_canvas">
	<div class="page_number"></div>

    <?php for ($counter = 1; $counter <= 4; $counter++): ?>
        <div class="dropspot droppable dropspot_<?= $counter ?>" id="dropspot_<?= $counter ?>" rel="<?= $counter ?>">
            <?= isset($data['dropspot_' . $counter]['item_id']) ? $block->getImage($data['dropspot_' . $counter]['item_id'], $images) : '' ?>
        </div>
        <div class="dropspot_number dropspot_number_<?= $counter ?>">(<?= $counter ?>)</div>
    <?php endfor; ?>

    <?php for ($counter = 1; $counter <= 4; $counter++): ?>
        <div class="dropspot_<?= $counter ?>_desc dropspot_desc">
            <?= (isset($data['dropspot_' . $counter]['item_id']) && isset($images[$data['dropspot_' . $counter]['item_id']]['desc'])) ? '('. $counter .')<br/>'.$images[$data['dropspot_' . $counter]['item_id']]['desc'] : '' ?>
        </div>
    <?php endfor; ?>
</div>