<?php
/**
 * RequisitionList Converted to Market Scans with project specific configurations
 * @copyright: Copyright © 2020 Perficient, Inc. All rights reserved.
 * @license: Perficient, Inc.
 * @author: Sachin Badase <sachin.badase@perficient.com>
 * @project: Wendover
 * @keywords:  Module Perficient_RequisitionList
 */
?>
<div class="requisition-list-title" data-bind="scope: 'requisition.action.edit.rename'">
    <h1><?= $block->escapeHtml($block->getRequisitionList()->getName()) ?></h1>
    <div class="requisition-list-description">
        <?= $block->escapeHtml($block->getRequisitionList()->getDescription()) ?>
    </div>
</div>

<div data-bind="scope: 'rename_requisition_list_popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition.action.edit.rename": {
                        "component": "Magento_RequisitionList/js/requisition/action/edit",
                        "editModuleName": "requisition_rename.edit"
                    },
                    "rename_requisition_list_popup": {
                        "component": "Magento_RequisitionList/js/requisition/list/edit/modal",
                        "options": {
                            "title": "<?= $block->escapeHtml(__('Rename Requisition List')) ?>"
                        },
                        "children": {
                            "form": {
                                "component": "Magento_RequisitionList/js/requisition/list/edit/form",
                                "template": "Magento_RequisitionList/requisition-list/form"
                            }
                        }
                    },
                    "requisition_rename.edit": {
                        "component": "Magento_RequisitionList/js/requisition/list/edit",
                        "modal": "rename_requisition_list_popup",
                        "saveUrl": "<?= $block->escapeUrl($block->getUrl('rest/V1/requisition_lists')) ?>"
                    }
                }
            }
        }
    }

</script>
