<?php
    $mediaUrl = $block->getMediaUrl();
    $product = $block->getCurrentProduct();
    $image_samples = [];
    for($i=1; $i <= 5; $i++){
      if($product->getData('image_sample_'.$i) && $product->getData('image_sample_'.$i) != "no_selection")
      $image_samples[] = $product->getData('image_sample_'.$i);
    }
?>
<?php if(count($image_samples) > 0): ?>
<div id="sample_images_custom_product">
    <hr/>
    <h3>Image Samples</h3>
    <div class="row">
    <div class="column samples-img-container">
      <?php foreach($image_samples as $image): ?>
        <div class="samples-img-div">
          <img class="view-image-samples" src="<?php echo $mediaUrl."catalog/product".$image ?>" alt="Sample image" title="Sample Image"/>
        </div>
      <?php endforeach; ?>
    </div>
    </div>
</div>
<?php endif; ?>