<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$productimizeHelper = $this->helper(\DCKAP\Productimize\Helper\Data::class);
$newProductImage = '';
if($item->getData('wishlist_item_id')){
    $newProductImage = $productimizeHelper->getImageurlforwishlistId($item->getData('wishlist_item_id'));
}
?>
<?php if($newProductImage == ''): ?>
<span class="product-item-photo productimize-img">
    <?= $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->toHtml() ?>
</span>
<?php else: ?>
    <span class="product-item-photo productimize-img">
        <span class="product-image-container product-image-container-2048" style="width: 270px;">
        <span class="product-image-wrapper" style="padding-bottom: 100%;">
            <img class="product-image-photo" src="<?=$newProductImage?>" loading="lazy" width="270" height="270" alt=""></span>
        </span>
    </span>
<?php endif; ?>
