<?php
/**
 *
 * This file used to remove title(WCAG Changes)
 *
 * @category: Magento
 * @package: Perficient/Company
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Company remove title
 */


/** @var $block Magento\Company\Block\Company\Management\Info */
?>
<?php if ($block->hasCustomerCompany() && $block->isUserEditAllowed()) : ?>
    <div class="actions">
        <button type="button"
                class="action primary"
                data-mage-init='{"Magento_Company/js/user-edit":{"gridProvider":"company_users_listing.company_users_listing_data_source"}}'
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Add New User')) ?>">
            <span><?= $block->escapeHtml(__('Add New User')) ?></span>
        </button>
    </div>
<?php endif; ?>
