<?php
/**
 * Remove Role and Status fields for Company Employee
 * @category: Magento
 * @package: Perficient/Company
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Sachin Badase <Sachin.Badase@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_Company
 */
?>
<?php
/** @var Magento\Company\Block\Company\Management\Add $block */
/** @var Magento\Company\ViewModel\Customer $viewModel */
$viewModel = $block->getData('viewModel');
$companyViewModel = $block->getData('company_view_model');
$getCurrentUserRole= $companyViewModel->getCurrentUserRole();
$isAdministrator = $companyViewModel::COMPANY_MASTER_ROLE;
$isAllowed = $companyViewModel->isAllowedMultiplier();
?>
<form class="form form-add-user" method="post" id="add-user-form"
      action="<?= $block->escapeUrl($block->getUrl('*/customer/manage')) ?>"
      data-mage-init='{"validation":{}}'>
    <input type="hidden" name="target_id" />
    <input type="hidden" name="customer_id" id="check_add_edit" />
    <?php if($getCurrentUserRole == $isAdministrator){?>
    <input type="hidden" name="is_administrator" id="is_administrator_<?php echo $companyViewModel->getCurrentLoggedInUserId();?>"/>
    <?php } ?>
    <fieldset class="fieldset info">
        <legend class="no-display"><?= $block->escapeHtml(__('Manage Customers')) ?></legend>
        <?php if($getCurrentUserRole == $isAdministrator){?>
        <?php if($companyViewModel->checkLink()== $companyViewModel::COMPANY_EMPLOYEE){?>
        <div class="field jobtitle" id="jobtitle_div">
            <label class="label" for="jobtitle">
                <span><?= $block->escapeHtml(__('Job Title')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="extension_attributes[company_attributes][job_title]"
                       id="jobtitle" value=""
                       autocomplete="organization-title"
                       title="<?= $block->escapeHtmlAttr(__('Job Title')) ?>"
                       class="input-text">
            </div>
        </div>
        <?php } ?>

        <?php } ?>
        <?= $viewModel->getCustomerNameHtml(); ?>
        <div class="field email required">
            <label class="label" for="email">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="email" id="email" value="" autocomplete="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       data-role="email"
                       data-url-validate="<?= $block->escapeUrl($block->getUrl('*/customer/check')) ?>"
                       class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php if($getCurrentUserRole == $isAdministrator){?>
            <?php if($companyViewModel->checkLink()== $companyViewModel::COMPANY_EMPLOYEE){?>
                <div class="field telephone" id="phone_div">
                    <label class="label" for="telephone">
                        <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="extension_attributes[company_attributes][telephone]" id="telephone" value=""
                               autocomplete="tel"
                               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                               class="input-text">
                    </div>
                </div>
                <?php if($isAllowed): ?>
                <div class="field price_multiplier" id="price_multiplier_div">
                    <label class="label" for="price_multiplier">
                        <span><?= $block->escapeHtml(__('Price Multiplier')) ?></span>
                    </label>
                    <div class="control">
                        <select data-role="price-multiplier-select" name="price_multiplier" id="price_multiplier" autocomplete="on">
                            <?php $options = $companyViewModel->getPriceMultiplierValues(); ?>
                            <?php foreach ($options as $value): ?>
                                <?php $selected = $value['value'] == '1.00'?'selected':'' ;?>
                                <option <?=$selected?> value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                                    <?= $block->escapeHtml($value['label']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <?php endif; ?>
            <?php } ?>
        <?php } ?>
        <?php if($companyViewModel->checkLink() == $companyViewModel::CUSTOMER_CUSTOMER){?>
        <div class="field price_multiplier" id="price_multiplier_div">
            <label class="label" for="price_multiplier">
                <span><?= $block->escapeHtml(__('Price Multiplier')) ?></span>
            </label>
            <div class="control">
                <select data-role="price-multiplier-select" name="price_multiplier" id="price_multiplier" autocomplete="on">
                   <?php $options = $companyViewModel->getPriceMultiplierValues(); ?>
                    <?php foreach ($options as $value): ?>
                        <option value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                            <?= $block->escapeHtml($value['label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
		<?php if ($companyViewModel->isDiscoutAvailable()) { ?>
            <input type="hidden" name="discount_available" id="discount_available" value="1" />
            <div class="field discount_type">
                <label class="label" for="discount_type">
                    <span><?= $block->escapeHtml(__('When to Apply Price Multiplier')) ?></span>
                </label>
                <div class="control">
                    <select data-role="discount_type-select" name="discount_type" id="discount_type" autocomplete="on">
                        <?php $options = $companyViewModel->getDiscountTypeValues(); ?>
                        <?php foreach ($options as $value): ?>
                            <option value="<?= $block->escapeHtmlAttr($value['value']) ?>">
                                <?= $block->escapeHtml($value['label']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php }} ?>
    </fieldset>
    <div id="additional_fields_create" data-role="create-additional-fields" class="_hidden additional-fields">
        <?= $block->getChildHtml('customer_form_user_attributes_create') ?>
    </div>
    <div id="additional_fields_edit" data-role="edit-additional-fields" class="_hidden additional-fields">
        <?= $block->getChildHtml('customer_form_user_attributes_edit') ?>
    </div>
</form>
<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            var currentUrl = ($(location).attr('href'));
            if(currentUrl.indexOf('resource_type=emp') != -1){
                var res = currentUrl.split("?");
                $('strong').contents().unwrap().wrap('<a href="'+res[0]+'"><a/>');
                $('a:contains("Manage Customers")').parent().removeClass('current');
                $('a:contains("<?php echo $companyViewModel::TITLE_EMPLOYEE_LOGINS;?>")').parent().addClass('current');
                $('.nav.item.current').contents().remove();
                $('.nav.item.current').append( $( "<strong><?php echo $companyViewModel::TITLE_EMPLOYEE_LOGINS;?></strong>" ) );
                $('.base').text("<?php echo $companyViewModel::TITLE_EMPLOYEE_LOGINS;?>");
            }else{
                $('.base').text("<?php echo $companyViewModel::TITLE_MANAGE_CUSTOMERS;?>");
            }
            <?php if($getCurrentUserRole == $companyViewModel::COMPANY_EMPLOYEE){ ?>
                $('a:contains("<?php echo $companyViewModel::TITLE_EMPLOYEE_LOGINS;?>")').parent().remove();
            <?php }?>
        })
    });
</script>
