<?php
/**
 *
 * This file used to add aria-label(WCAG Changes)
 *
 * @category: Magento
 * @package: Perficient/Review
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Review add aria-label
 */


/**
 * @var \Magento\Review\Block\Customer\Recent $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="block block-reviews-dashboard">
        <div class="block-title">
            <h2 class="heading-l2"><?= $block->escapeHtml(__('My Recent Reviews')) ?></h2>
            <a class="action view" aria-label="<?= $block->escapeHtml(__('View All My Recent Reviews')) ?>" href="<?= $block->escapeUrl($block->getAllReviewsUrl()) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        </div>
        <div class="block-content">
            <ol class="items">
                <?php foreach ($block->getReviews() as $_review): ?>
                    <li class="item">
                        <strong class="product-name">
                            <a href="<?= $block->escapeUrl($block->getReviewUrl($_review->getReviewId())) ?>">
                                <?= $block->escapeHtml($_review->getName()) ?>
                            </a>
                        </strong>
                        <?php if ($_review->getSum()): ?>
                            <?php $rating = $_review->getSum() / $_review->getCount() ?>
                            <div class="rating-summary">
                                <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                                <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating) ?>%">
                             <span>
                                 <span><?= $block->escapeHtml($rating) ?>%</span>
                             </span>
                                </div>
                                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                    "width:". $block->escapeHtmlAttr($rating) . "%",
                                    'div.rating-result>span:first-child'
                                ) ?>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
