<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\ProductAlert\Block\Email\Stock */
?>
<?php if ($_products = $block->getProducts()) : ?>
    <p><?= $block->escapeHtml(__('In stock alert! We wanted you to know that following product(s) are now available:')) ?></p>
    <table>
        <?php foreach ($_products as $_product) : ?>
            <tr>
                <td class="col photo">
                    <?= $block->getImage($_product, 'product_thumbnail_image', ['class' => 'photo image'])->toHtml() ?>
                </td>
                <td class="col item">
                    <p>
                        <strong class="product name">
                            <?= $block->escapeHtml($_product->getName()) ?>
                        </strong>
                    </p>
                    <?php if ($shortDescription = $block->getFilteredContent($_product->getShortDescription())) : ?>
                        <p><small><?= /* @noEscape */  $shortDescription ?></small></p>
                    <?php endif; ?>
                    <?=
                    $block->getProductPriceHtml(
                        $_product,
                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                        \Magento\Framework\Pricing\Render::ZONE_EMAIL,
                        [
                            'display_label' => __('Price:')
                        ]
                    );
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
