<?php

use Magento\Wishlist\Block\Customer\Wishlist\Items;
use Perficient\Wishlist\ViewModel\WishListProductViewModel;

/** @var Items $block */
$columns = $block->getColumns();
/** @var WishListProductViewModel $viewModel */
$viewModel = $block->getViewModel();
?>

<div class="products-grid wishlist">
    <?php if (count($block->getItems())) : ?>
        <ol class="product-items">
            <?php foreach ($block->getItems() as $item) : ?>
                <?php $product = $viewModel?->getSimpleProduct($item) ?: $item->getProduct() ?>
                <li data-row="product-item" class="product-item" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                    <div class="product-item-info" data-container="product-grid">
                        <?php foreach ($columns as $column) : ?>
                            <?= $column->setItem($item)->setProduct($product)->toHtml();?>
                        <?php endforeach; ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else : ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column) : ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
