<?php
/**
 * Make Company Name un-editable
 * @category: Magento
 * @package: Perficient/Company
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Vikramraj Sahu<vikramraj.sahu@perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient_Company
 */
?>
<fieldset class="fieldset company">
    <legend class="no-display"><?= $block->escapeHtml(__('Company')) ?></legend>
    <div class="field">
        <label class="label" for="company"><span>
            <?= $block->escapeHtml(__('Company')) ?></span>
        </label>
        <div class="control">

            <label class="label"><?= $block->escapeHtmlAttr($block->getCompanyName()) ?></label>
            <input id="company" type="hidden" class="input-text readonly" name="company"
                   value="<?= $block->escapeHtmlAttr($block->getCompanyName()) ?>" readonly="readonly"/>
        </div>
    </div>
</fieldset>
<fieldset class="fieldset job_title">
    <legend class="no-display"><?= $block->escapeHtml(__('Job Title')) ?></legend>
    <div class="field">
        <label class="label" for="job_title"><span>
            <?= $block->escapeHtml(__('Job Title')) ?></span></label>
        <div class="control">
            <input type="text" id="job_title" autocomplete="organization-title" class="input-text" name="customer[extension_attributes][company_attributes][job_title]"
                   value="<?= $block->escapeHtmlAttr($block->getJobTitle()) ?>"/>
        </div>
    </div>
</fieldset>
