<?php
/**
 *
 * This file used to add legend(WCAG Changes)
 *
 * @category: Magento
 * @package: Perficient/CustomerCustomAttributes
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module CustomerCustomAttributes add legend
 */

?>
<?php
/**
 * Create account form template
 *
 * @see \Magento\CustomerCustomAttributes\Block\Form
 */
/* @var $block \Magento\CustomerCustomAttributes\Block\Form */
?>
<?php if ($block->hasUserDefinedAttributes()) : ?>
    <?php if ($block->isShowContainer()) : ?>
        <fieldset class="fieldset">
        <legend class="no-display"><?= $block->escapeHtml(__('Legend')) ?></legend>
    <?php endif;?>
    <?php foreach ($block->getUserDefinedAttributes() as $attribute) :?>
        <?php $attributeContent = $block->getAttributeHtml($attribute);?>
        <?php if ($attributeContent) : ?>
            <?= /* @noEscape */ $attributeContent ?>
        <?php endif;?>
    <?php endforeach;?>
    <?php if ($block->isShowContainer()) : ?>
        </fieldset>
    <?php endif;?>
<?php endif; ?>
