<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Customer "Remember Me" template
 */

/** @var \Magento\Persistent\Block\Form\Remember $block */

?>
<div id="remember-me-box" class="field choice persistent">
    <?php $rememberMeId = 'remember_me' . $block->getRandomString(10); ?>
    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?= $block->escapeHtmlAttr($rememberMeId) ?>" <?php if ($block->isRememberMeChecked()) : ?> checked="checked" <?php endif; ?>  />
    <label for="<?= $block->escapeHtmlAttr($rememberMeId) ?>" class="label"><span><?= $block->escapeHtml(__('Remember Me')) ?></span></label>

    <div class="what-this-tooltip-wrapper field-tooltip tooltip wrapper">
        <a  class="field-tooltip-action what-this-tooltip"
           tabindex="0"
           data-toggle="dropdown"
           data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}" data-trigger-keypress-button="true" role="button">
            <span class="tooltip toggle"> <?= $block->escapeHtml(__('What\'s this?')) ?></span>
        </a>
        <div role="dialog" class="field-tooltip-content"
             data-target="dropdown">
            <a tabindex="0" class="close-icon" aria-label="Close" data-action-keypress="true" role="button"></a>
            <span> <?= $block->escapeHtml(__('Check &quot;Remember Me&quot; to access your shopping cart on this computer even if you are not signed in.')) ?></span>
        </div>
    </div>
</div>
