<?php
/**
 * Added legend and id on multiple field
 * @category: PHP HTML
 * @package: Perficient/MailChimp
 * @copyright: Copyright © 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: Purushottam Rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Ebizmarts_MailChimp
 */
/**
 * @var $block \Ebizmarts\MailChimp\Block\Newsletter
 */
$interest = $block->getInterest();
?>
<fieldset class="fieldset">
    <legend class="no-display"><?php echo $block->escapeHtml(__('General Subscription')) ?></legend>
    <?php foreach($interest as $i): ?>
        <div class="field">
            <label class="label" for="<?php echo $i['interest']['id'] ?>">
                <span><?php echo $i['interest']['title'] ?></span>
            </label>
            <div class="control">
                <div class="fields">
                    <?php switch($i['interest']['type']):
                        case 'checkboxes': ?>
                            <ul class="field" style="list-style: none">
                                <?php foreach($i['category'] as $c): ?>
                                    <li class="field no-label">
                                        <input class=""
                                               name="group[<?php echo $i['interest']['id'] ?>][<?php echo $c['id']?>]"
                                               type="checkbox"
                                               value="<?php echo $c['id'] ?>"
                                               id="<?php echo 'mailchimp_group_'.$c['id'] ?>"
                                            <?php if($c['checked']) { echo 'checked';} ?>
                                        />
                                        <label for="<?php echo 'mailchimp_group_'.$c['id'] ?>" class="field label"><?php echo $c['name']?></label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php       break;
                        case 'dropdown': ?>
                            <div class="field no-label">
                                <select class="field"
                                        name="group[<?php echo $i['interest']['id'] ?>]"
                                        id="<?php echo 'mailchimp_group_'.$i['interest']['id'] ?>"
                                       >
                                    <option value=""></option>
                                    <?php foreach($i['category'] as $c): ?>
                                        <option value="<?php echo $c['id']?>" <?php if($c['checked']) { echo 'selected'; } ?>><?php echo $c['name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <label for="<?php echo 'mailchimp_group_'.$i['interest']['id'] ?>" class="label no-label"><?php echo $c['name'] ?></label>
                            </div>
                            <?php       break;
                        case 'radio': ?>
                            <ul class="field">
                                <?php foreach($i['category'] as $c): ?>
                                    <li class="field no-label" style="list-style: none">
                                        <input class=""
                                               name="group[<?php echo $i['interest']['id'] ?>]"
                                               type="radio"
                                               value="<?php echo $c['id'] ?>"
                                               id="<?php echo 'mailchimp_group_'.$c['id'] ?>"
                                            <?php if($c['checked']) { echo 'checked';} ?>
                                        />
                                        <label for="<?php echo 'mailchimp_group_'.$c['id'] ?>" class="field label"><?php echo $c['name']?></label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php       break; ?>
                        <?php endswitch; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</fieldset>
