<?php
$_item = $block->getItem();
$product = $_item->getProduct(); // Get cart product details

?>
<div>

    <?php
    $options = $block->getItem()->getBuyRequest();

    if (isset($options['pz_cart_properties']) && !empty($options['pz_cart_properties'])) {
        $promizeCartProperties = json_decode($options['pz_cart_properties'],1);
        $promizeCustomizedImage = $promizeCartProperties[' CustomImage'];
    ?>

        <div class="image-modal-wrapper">
            <?php
            if ($promizeCustomizedImage) {
                ?>
                <img src ="<?php //echo $promizeCustomizedImage;?>" height="300" width="300" />
            <?php
            }
            ?>

        </div>

        <?php

        $inc = 0;

        foreach ($promizeCartProperties as $key => $value) {
            $inc++;
            if ($inc  == 1) {
                echo "<table style='width:50%'>";
            }

            if ($key == ' CustomImage')
            {
                echo "<tr><td><b>Designed Image</b></td> <td>:</td> <td><a href='".$value."'>Designed Image</a></td></tr> ";
            }
            else {
                echo "<tr><td><b>$key</b></td> <td>:</td> <td>$value</td></tr> ";
            }

            if (count($promizeCartProperties) == $inc) {
                echo "</table>";

            }
        }
    }

    ?>

</div>
