<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Wendover\Theme\ViewModel\WendoverViewModel $viewModel */
?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<?php
$product = $block->getItem()->getOrderItem()->getProduct();
$productUrl = $product->getUrlModel()->getUrl($product);
?>

<?php
$imageUrl = '';
$customizedDataArray = [];
if($block->getItem()->getOrderItem()->getProductOptionByCode('info_buyRequest') !== null) {
    $buyRequest = $block->getItem()->getOrderItem()->getProductOptionByCode('info_buyRequest');

    $viewModel = $block->getData('wendover_model');
    $imageUrl = $viewModel->getImageUrlFromBuyRequestData($buyRequest);

    if(!empty($buyRequest) && isset($buyRequest['edit_id'])) {
        $customizeEditId = $buyRequest['edit_id'];
    }

    if(isset($buyRequest['pz_cart_properties']) && $buyRequest['pz_cart_properties']) {
        $customizedDataArray = $viewModel->getValidCustomizedOptions($buyRequest['pz_cart_properties']);
    }
}
$miscSku = strtolower($block->getSku());
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')) ?>">
        <div class="order-detail-name">
            <?php if($miscSku == "misc"):?>
                <strong class="product name product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
            <?php else : ?>
                <a href="<?= $escaper->escapeUrl($productUrl) ?>">
                    <strong class="product name product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
                </a>
            <?php endif; if (isset($customizeEditId)) :?>
                <img src="<?= $block->getViewFileUrl('Perficient_Order/images/icon.palette.svg'); ?>" alt="" style="padding-left: 10px;vertical-align: middle;" />
                <span class="customized-name" style="margin-left: 1rem;"><?= $block->escapeHtml(__('Customized')) ?></span>
            <?php endif; ?>
        </div>
        <!-- <table>
        <tr>
        <td style="width:80%"> -->
        <?php if (!empty($customizedDataArray['dataArray'])) : ?>
            <dl class="item-options">
                <?php foreach ($customizedDataArray['dataArray'] as $labelKey => $labelValue) :?>
                    <dt><?= $escaper->escapeHtml($labelKey) ?></dt>
                    <dd>
                        <?= $labelValue ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php elseif ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <?php
                    // Condition for weighted Mats - Removed the tooltip class
                    if (isset($_formatedOptionValue['full_view']) && (strpos(strtolower($block->stripTags($_option['value'])), 'weighted') !== false)): ?>
                    <dd>
                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a', 'img','span', 'i']) ?>
                    </dd>
                    <?php else: ?>

                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                            <div class="tooltip content">
                                <dl class="item options">
                                    <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                                    <dd><?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                </dl>
                            </div>
                            <?php endif; ?>
                        </dd>
                    <?php endif;?>
                <?php else : ?>
                    <dd>
                        <?= $escaper->escapeHtml($_option['print_value'] ?? $_option['value']) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>

        <?php /* downloadable */ ?>
        <?php if ($links = $block->getLinks()) : ?>
            <dl class="item options">
                <dt><?= $escaper->escapeHtml($block->getLinksTitle()) ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link) : ?>
                    <dd><?= $escaper->escapeHtml($link->getLinkTitle()) ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* EOF downloadable */ ?>
        <!-- </td>
        <td style="width:20%;">                 -->
        <?php if($imageUrl != ''): ?>
            <img width="100" height="100" style="display: block;" src="<?=$imageUrl?>" />
        <?php else:
            $imgUrl = $viewModel->getImageURL($product, 'product_thumbnail_image');
        ?>
        <img width="100" height="100" style="display: block;" src="<?=$imgUrl?>" alt="" />
        <?php endif; ?>
        <!-- </td>
        </tr>
        </table> -->
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>"><?= (float) $_item->getQty() ?></td>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
    <td class="col discount" data-th="<?= $escaper->escapeHtml(__('Discount Amount')) ?>"><?= /* @noEscape */ $_order->formatPrice(-$_item->getDiscountAmount()) ?></td>
    <td class="col total" data-th="<?= $escaper->escapeHtml(__('Row Total')) ?>">
        <?= $block->getItemRowTotalAfterDiscountHtml() ?>
    </td>
</tr>
