<?php
/**
 *
 * This file used to changes in search listing toolbar
 *
 * @category: Magento
 * @package: Perficient/Catalog
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: harshal dantalwar <harshal.dantalwar@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient catalog toolbar
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->isEnabledViewSwitcher()) :?>
    <div class="modes">
        <?php $_modes = $block->getModes(); ?>
        <?php if ($_modes && count($_modes) > 1) :?>
            <strong class="modes-label" id="modes-label" aria-label="<?= $block->escapeHtml(__('View as')) ?>">
                <?= $block->escapeHtml(__('View')) ?>
            </strong>
            <?php foreach ($block->getModes() as $_code => $_label) :?>
                <?php if ($block->isModeActive($_code)) :?>
                    <strong
                            class="modes-mode active mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                            data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </strong>
                <?php else :?>
                    <a class="modes-mode mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       href="#"
                       data-role="mode-switcher"
                       data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       id="mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
