<?php
/**
 *
 * This file used to Add Paragraph
 *
 * @category: Magento
 * @package: Perficient/Company
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Company
 */
?>
<?php /** @var $block \Magento\Company\Block\Company\Login\Info */ ?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block block-new-company">
        <div class="block-title">
            <strong role="heading" aria-level="2" id="block-new-company-heading"><?= $block->escapeHtml(__('New Company Account')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-company-heading">
            <p>
                <?= $block->escapeHtml(__(
                    'If you represent a company, you will want to use our company account area. ' .
                    'Creating a company account provides all company members with access to B2B features like quoting, ' .
                    'company users management, quick order, and more.'
                )) ?>
            </p>
            <p>
                <?= $block->escapeHtml(__(
                    'If your company is already registered with Wendover Art Group, please contact your company administrator to request a user login.'
                )) ?>
            </p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                       class="action create primary">
                        <span><?= $block->escapeHtml(__('Create a Company Account')) ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
