<?php
/**
 *
 * This file used to add autocomplete
 *
 * @category: Magento
 * @package: Perficient/CustomerCustomAttributes
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient Customer Custom Attributes
 */
?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Select */
?>
<?php
$fieldCssClass = 'field field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= /* @noEscape */ $fieldCssClass ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    <div class="control">
        <select autocomplete="on" id="<?= $block->getHtmlId() ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName()) ?>"<?php if ($block->getHtmlClass()) :
            ?> class="select <?= $block->getHtmlClass() ?>"<?php endif;?>>
        <?php foreach ($block->getOptions() as $option) :?>
        <?php if (empty($option['value'])): continue; endif; ?>
        <option value="<?= $block->escapeHtmlAttr($option['value']) ?>"<?php if ($option['value'] == $block->getValue()) :
            ?> selected="selected"<?php endif;?>><?= $block->escapeHtml($option['label']) ?></option>
        <?php endforeach;?>
        </select>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?= /* @noEscape */ $_message ?></div>
        <?php endif; ?>
    </div>
</div>
