<?php
/**
 *
 * This file used to add autocomplete
 *
 * @category: Magento
 * @package: Perficient/CustomerCustomAttributes
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: purushottam rathi <purushottam.rathi@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient Customer Custom Attributes
 */
?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Text */
?>
<?php
$fieldCssClass = 'field field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= /* @noEscape */ $fieldCssClass ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    <div class="control">
        <input type="text" autocomplete="on" id="<?= $block->getHtmlId() ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName()) ?>" value="<?= /* @noEscape */ $block->getEscapedValue() ?>" class="input-text<?= $block->getHtmlClass() ?>">
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?= /* @noEscape */ $_message ?></div>
        <?php endif; ?>
    </div>
</div>
