<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Perficient\Order\Block\Item\Renderer */
$_item = $block->getItem();
$buyRequest = $_item->getBuyRequest()->getData();
$productimizeHelper = $this->helper(\DCKAP\Productimize\Helper\Data::class);
$imageUrl = $productimizeHelper->getImageurlfrombuyrequestdata($buyRequest);

if(!empty($buyRequest) && isset($buyRequest['edit_id'])) {
    $customizeEditId = $buyRequest['edit_id'];
}
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name">
            <?= $block->escapeHtml($_item->getName()) ?>
            <?php if (isset($customizeEditId)) :?>
                <img src="<?= $block->getViewFileUrl('Perficient_Order/images/icon.palette.svg'); ?>" alt="" style="padding-left: 10px;vertical-align: middle;" />
                <span class="customized-name" style="margin-left: 1rem;"><?= $block->escapeHtml(__('Customized')) ?></span>
            <?php endif; ?>
        </strong>
        <?php if($imageUrl != ''): ?>
            <div class="productimize_added_element_container_myaccount">
                <?php endif; ?>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>

                        <?php
                        $matValues = array("Top Mat","Bottom Mat","Frame");
                        if(in_array($_option['label'], $matValues) && (isset($_formatedOptionValue['full_view']))): ?>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dd><?= $block->escapeHtml($_formatedOptionValue['full_view'],['span', 'i']) ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                            <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php endif; ?>
                    <?php else : ?>
                        <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
                <?php if($imageUrl != ''): ?>
                <img width="140" height="140" style="display: block" src="<?=$imageUrl?>" />
            </div>
                <?php else: ?>
                    <?= $block->getProductImage($_item,'cart_page_product_thumbnail')->toHtml() ?>
                <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
                </div>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
                <div class="item">
                    <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
                </div>
            <?php endif; ?>
        </div>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
