<?php
/**
 * This module is used to add title in page
 * @category: Magento
 * @package: Perficient/magento Wishlist
 * @copyright: Copyright  - 2020 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @license: Magento Enterprise Edition (MEE) license
 * @author: harshal dantalwar <harshal.dantalwar@Perficient.com>
 * @project: Wendover
 * @keywords: Module Perficient Wishlist
 */
$CollaborationName = $block->getLayout()->createBlock('Perficient\Wishlist\Block\Customer\Collaboration');
?>
<?php if ($CollaborationName->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items" id="wishlist-view-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId(), 'page_type' => "collaboration"])) ?>" method="post">
        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()) : ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your favorites.')) ?></span></div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <?= $block->getChildHtml('control_buttons') ?>
            </div>
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
        <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
            <% if (data.qty) { %>
            <input name="qty" value="<%- data.qty %>">
            <% } %>

            <% if (data.item) { %>
            <input name="item" value="<%- data.item %>">
            <% } %>

            <% if (data.entity) { %>
            <input name="entity" value="<%- data.entity %>">
            <% } %>
        </form>
    </script>
    <div class="toolbar wishlist-toolbar"><br><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
<?php endif ?>
