<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<?php
/** @var \Amasty\MegaMenu\Block\Html\Topmenu $block */
?>
<?php if (!$block->isHamburgerEnabled()): ?>
    <section class="ammenu-menu-wrapper -mobile"
             data-ammenu-js="mobile-menu">
        <nav class="ammenu-main-container" data-ammenu-js="tab-content">
            <ul class="ammenu-items" data-ammenu-js="menu-items" role="menubar">
                <?php
                foreach ($block->getMainNodes() as $mainNode):
                    if (!$block->isNeedDisplay($mainNode->getId(), $mainNode->getStatus(), $block::MOBILE_VIEW)) {
                        continue;
                    }
                    $url = $mainNode->getUrl() ?: '#';
                    $mainNodeContent = $block->getCategoriesHtml($mainNode);
                    ?>
                    <li class="ammenu-item category-item -main <?= $block->escapeHtml($mainNode->getPositionClass()); ?>" data-ammenu-js="item" role="none">
                        <a href="<?= $block->escapeUrl($url); ?>" role="menuitem"
                           class="ammenu-link -main<?= ($mainNodeContent) ? ' -parent' : '' ?>
                       <?= /* @noEscape */ $block->getHighLightClass($mainNode); ?>">
                            <span class="ammenu-wrapper"><?= $block->escapeHtml($mainNode->getName()); ?></span>
                        </a>
                        <?php if ($mainNodeContent): ?>
                            <div class="ammenu-toggle" aria-expanded="false" role="button" aria-haspopup="true" data-ammenu-js="collapse-trigger">
                                <span class="ammenu-icon" data-ammenu-js="collapse-indicator"></span>
                            </div>
                        <?php endif; ?>
                        <?php if ($mainNodeContent): ?>
                            <div class="ammenu-submenu-container ammenu-submenu" data-ammenu-js="collapse-content">
                                <?= /* @noEscape */ $mainNodeContent; ?>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </section>
<?php endif; ?>