<?php
/**
 * RequisitionList Converted to Market Scans with project specific configurations
 * @copyright: Copyright © 2020 Perficient, Inc. All rights reserved.
 * @license: Perficient, Inc.
 * @author: Sachin Badase <sachin.badase@perficient.com>
 * @project: Wendover
 * @keywords:  Module Perficient_RequisitionList
 */

/* @var $block \Magento\RequisitionList\Block\Link\Lists */
?>
<?php
$blockName = $block->getLayout()->createBlock('Perficient\RequisitionList\Block\Requisition\View\Item');
$getUserCurrentRole = $blockName->getCurrentUserRole();
if(isset($getUserCurrentRole[0]) && $getUserCurrentRole[0] != Perficient\Company\Helper\Data::CUSTOMER_CUSTOMER){
?>
<!-- ko scope: 'requisition' -->
<!-- ko if: requisition().is_enabled-->
<li>
    <a href="<?= $block->escapeUrl($block->getHref()) ?>">
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
<!-- /ko -->
<!-- /ko -->
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition": {
                        "component": "Magento_RequisitionList/js/requisition"
                    }
                }
            }
        }
    }
</script>
<?php } ?>