<?php
/**
 *
 * @category: Perficient's Extension
 * @package: Perficient\CronScheduler
 * @copyright: Copyright © 2018 Perficient, Inc. All rights reserved.
 * @license: Perficient, Inc.
 * @author: Sandip Titarmare<sandip.titarmare@perficient.com>
 * @keywords: cron list, enables and disables specific crons
 */
?>
<div id="task-view" style="display: none;" class="messages">
    <span id="error" class="error"></span>
    <table>
        <tr id="tr-task-schedule_id"><td><label><?php echo __('Task #'); ?></label></td><td><span id="task-schedule_id"></span></td></tr>
        <tr id="tr-task-job_code"><td><label><?php echo __('Job code'); ?></label></td><td><span id="task-job_code"></span></td></tr>
        <tr id="tr-task-status"><td><label><?php echo __('Status'); ?></label></td><td><span id="task-status"></span></td></tr>
        <tr id="tr-task-created_at"><td><label><?php echo __('Created at'); ?></label></td><td><span id="task-created_at"></span></td></tr>
        <tr id="tr-task-scheduled_at"><td><label><?php echo __('Scheduled at'); ?></label></td><td><span id="task-scheduled_at"></span></td></tr>
        <tr id="tr-task-executed_at"><td><label><?php echo __('Executed at'); ?></label></td><td><span id="task-executed_at"></span></td></tr>
        <tr id="tr-task-finished_at"><td><label><?php echo __('Finished at'); ?></label></td><td><span id="task-finished_at"></span></td></tr>
        <tr id="tr-task-messages"><td><label><?php echo __('Messages'); ?></label></td><td><span id="task-messages"></span></td></tr>
    </table>
</div>
