<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\CompanyPayment\Block\Company\Profile\PaymentMethod $block
 */
?>

<div class="block block-company-profile-payment-methods">
    <h2 class="block-title heading-l2">
        <strong><?= $block->escapeHtml(__('Payment Information')) ?></strong>
    </h2>
    <div class="block-content">
        <?php
        if ($block->hasPaymentMethods()) : ?>
            <div class="company-profile-payment-methods">
                <h3 class="payment-methods-label box-title heading-l3">
                    <?= $block->escapeHtml(__('Available Payment Methods')) ?>
                </h3>
                <ul class="payment-methods-list">
                    <?php foreach ($block->getPaymentMethods() as $paymentMethod) : ?>
                        <li><?= $block->escapeHtml($paymentMethod) ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php else : ?>
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                    <?= $block->escapeHtml(__('This company has no payment methods. Please contact store administrator.')) ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
